### ISSUE TITLE
After upgrading to 2.5.0, markmap doesn't render properly anymore

### ISSUE THREAD

**Issue by jaywhj** [markmap/mkdocs-markmap#65]
Uncaught TypeError: transformer.getPreloadScripts is not a function：

![Image](https://github.com/user-attachments/assets/cbc29cec-bdfa-4e18-aa6e-4cea75fa37c8)

**Comment by neatc0der** [comment]
@gera2ld, any thoughts? I merely wrapped a release around your fix.

**Comment by gera2ld** [comment]
Sorry my bad, let me fix it.

**Comment by jaywhj** [comment]
@neatc0der 

Problem fixed, thanks a lot. 

But got another warning message, see if this has any impact on the project?

```bash
INFO    -  DeprecationWarning: Call to deprecated method findChild. (Replaced by find) -- Deprecated since version 3.0.0.
             File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/mkdocs_markmap/plugin.py", line
           124, in on_page_content
               code = markmap.findChild("code")
             File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bs4/_deprecation.py", line 56,
           in alias
               warnings.warn(
INFO    -  markmap found: markmap-mkdocs
INFO    -  Documentation built in 1.14 seconds
```
